// <auto-generated />
using System;
using ESTeSoccer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESTeSoccer.Migrations
{
    [DbContext(typeof(ESTeSoccerContext))]
    [Migration("20220107083041_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ESTeSoccerMVC.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LeagueId");

                    b.ToTable("League");

                    b.HasData(
                        new
                        {
                            LeagueId = 1,
                            Country = "Portugal",
                            Name = "Liga Bwin"
                        },
                        new
                        {
                            LeagueId = 2,
                            Country = "Inglaterra",
                            Name = "Premier League"
                        });
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 25000000m,
                            Name = "Pote",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 15000000m,
                            Name = "Paulinho",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 3,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 10000000m,
                            Name = "Francisco Conceição",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 4,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 25000000m,
                            Name = "Luis Diaz",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 5,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 25000000m,
                            Name = "Rafa",
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 6,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 20000000m,
                            Name = "Grimaldo",
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 7,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 45000000m,
                            Name = "Lukaku",
                            TeamId = 4
                        },
                        new
                        {
                            PlayerId = 8,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 25000000m,
                            Name = "Harvertz",
                            TeamId = 4
                        },
                        new
                        {
                            PlayerId = 9,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 100000000m,
                            Name = "De Bruyne",
                            TeamId = 5
                        },
                        new
                        {
                            PlayerId = 10,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 45000000m,
                            Name = "Bernardo Silva",
                            TeamId = 5
                        },
                        new
                        {
                            PlayerId = 11,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 75000000m,
                            Name = "Ronaldo",
                            TeamId = 6
                        },
                        new
                        {
                            PlayerId = 12,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 80000000m,
                            Name = "Bruno Fernandes",
                            TeamId = 6
                        },
                        new
                        {
                            PlayerId = 13,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 200000000m,
                            Name = "Salah",
                            TeamId = 7
                        },
                        new
                        {
                            PlayerId = 14,
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 50000000m,
                            Name = "Diogo Jota",
                            TeamId = 7
                        });
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"), 1L, 1);

                    b.Property<DateTime?>("FoundingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("MainColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTitles")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Initials = "SCP",
                            LeagueId = 1,
                            MainColor = "Verde",
                            Name = "Sporting",
                            NumberOfTitles = 19
                        },
                        new
                        {
                            TeamId = 2,
                            Initials = "FCP",
                            LeagueId = 1,
                            MainColor = "Azul",
                            Name = "Porto",
                            NumberOfTitles = 29
                        },
                        new
                        {
                            TeamId = 3,
                            Initials = "SLB",
                            LeagueId = 1,
                            MainColor = "Vermelho",
                            Name = "Benfica",
                            NumberOfTitles = 35
                        },
                        new
                        {
                            TeamId = 4,
                            Initials = "CHE",
                            LeagueId = 2,
                            MainColor = "Azul",
                            Name = "Chelsea",
                            NumberOfTitles = 3
                        },
                        new
                        {
                            TeamId = 5,
                            Initials = "MCI",
                            LeagueId = 2,
                            MainColor = "Azul",
                            Name = "Manchester City",
                            NumberOfTitles = 6
                        },
                        new
                        {
                            TeamId = 6,
                            Initials = "MUN",
                            LeagueId = 2,
                            MainColor = "Vermelho",
                            Name = "Manchester United",
                            NumberOfTitles = 35
                        },
                        new
                        {
                            TeamId = 7,
                            Initials = "LIV",
                            LeagueId = 2,
                            MainColor = "Vermelho",
                            Name = "Liverpool",
                            NumberOfTitles = 35
                        });
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.Player", b =>
                {
                    b.HasOne("ESTeSoccerMVC.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.Team", b =>
                {
                    b.HasOne("ESTeSoccerMVC.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ESTeSoccerMVC.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
