// <auto-generated />
using System;
using ESTeSoccer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESTeSoccer.Migrations
{
    [DbContext(typeof(ESTeSoccerContext))]
    [Migration("20211126114858_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESTeSoccer.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("LeagueId");

                    b.ToTable("League");

                    b.HasData(
                        new
                        {
                            LeagueId = 1,
                            Country = "Portugal",
                            Name = "Liga Bwin"
                        },
                        new
                        {
                            LeagueId = 2,
                            Country = "Inglaterra",
                            Name = "Premier League"
                        });
                });

            modelBuilder.Entity("ESTeSoccer.Models.Player", b =>
                {
                    b.Property<int>("Playerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<double>("MarketValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Playerid");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Playerid = 1,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Alex",
                            TeamId = 1
                        },
                        new
                        {
                            Playerid = 2,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Alex2",
                            TeamId = 1
                        },
                        new
                        {
                            Playerid = 3,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Figo",
                            TeamId = 2
                        },
                        new
                        {
                            Playerid = 4,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Figo2",
                            TeamId = 2
                        },
                        new
                        {
                            Playerid = 9,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Cristiano Ronaldo",
                            TeamId = 5
                        },
                        new
                        {
                            Playerid = 10,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Cristiano Ronaldo2",
                            TeamId = 5
                        },
                        new
                        {
                            Playerid = 5,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Ronaldo",
                            TeamId = 3
                        },
                        new
                        {
                            Playerid = 6,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Ronaldo2",
                            TeamId = 3
                        },
                        new
                        {
                            Playerid = 7,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Salah",
                            TeamId = 4
                        },
                        new
                        {
                            Playerid = 8,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Salah2",
                            TeamId = 4
                        },
                        new
                        {
                            Playerid = 11,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Bernardo Silva",
                            TeamId = 6
                        },
                        new
                        {
                            Playerid = 12,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Bernardo Silva2",
                            TeamId = 6
                        },
                        new
                        {
                            Playerid = 13,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Jorginho",
                            TeamId = 7
                        },
                        new
                        {
                            Playerid = 14,
                            DateOfBirth = new DateTime(1998, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarketValue = 2.0,
                            Name = "Jorginho2",
                            TeamId = 7
                        });
                });

            modelBuilder.Entity("ESTeSoccer.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("MainColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTitles")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            FoundingDate = new DateTime(1896, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "FCP",
                            LeagueId = 1,
                            MainColor = "Azul",
                            Name = "Porto",
                            NumberOfTitles = 40
                        },
                        new
                        {
                            TeamId = 2,
                            FoundingDate = new DateTime(1904, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "SLB",
                            LeagueId = 1,
                            MainColor = "Vermelho",
                            Name = "Benfica",
                            NumberOfTitles = 40
                        },
                        new
                        {
                            TeamId = 3,
                            FoundingDate = new DateTime(1906, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "SCP",
                            LeagueId = 1,
                            MainColor = "Verde",
                            Name = "Sporting",
                            NumberOfTitles = 40
                        },
                        new
                        {
                            TeamId = 5,
                            FoundingDate = new DateTime(1906, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "MAN",
                            LeagueId = 2,
                            MainColor = "Vermelho",
                            Name = "Manchester United",
                            NumberOfTitles = 100
                        },
                        new
                        {
                            TeamId = 6,
                            FoundingDate = new DateTime(1906, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "MCT",
                            LeagueId = 2,
                            MainColor = "azul",
                            Name = "Manchester City",
                            NumberOfTitles = 100
                        },
                        new
                        {
                            TeamId = 7,
                            FoundingDate = new DateTime(1906, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "CHL",
                            LeagueId = 2,
                            MainColor = "azul",
                            Name = "Chelsea",
                            NumberOfTitles = 100
                        },
                        new
                        {
                            TeamId = 4,
                            FoundingDate = new DateTime(1906, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Initials = "LFP",
                            LeagueId = 2,
                            MainColor = "Vermelho",
                            Name = "Liverpool",
                            NumberOfTitles = 100
                        });
                });

            modelBuilder.Entity("ESTeSoccer.Models.Player", b =>
                {
                    b.HasOne("ESTeSoccer.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ESTeSoccer.Models.Team", b =>
                {
                    b.HasOne("ESTeSoccer.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
