n1:
	gcc -g -o prog main1.c disk.c move.c
n2:
	gcc -g -o prog main2.c disk.c move.c hanoiGame.c stackArrayList.c stackElem.c
n3:
	gcc -g -o prog main3.c disk.c move.c hanoiGame.c stackArrayList.c stackElem.c
n4:
	gcc -g -o prog main4.c disk.c move.c hanoiGame.c stackArrayList.c stackElem.c	
n5:
	gcc -g -o prog main5.c disk.c move.c hanoiGamePlus.c stackArrayList.c stackElem.c queueElem.c queueArrayList.c	
clear:
	rm -f prog