n2:
	gcc -g -o prog main2.c kahootReport.c utils.c listElem.c listArrayList.c kahootStatistic.c stringCode.c mapElem.c mapArrayList.c
n1:
	gcc -g -o prog main1.c stringCode.c
n3:
	gcc -g -o prog main3.c kahootReport.c utils.c listElem.c listArrayList.c kahootStatistic.c statisticsUtils.c stringCode.c mapElem.c mapArrayList.c
n4:
	gcc -g -o prog main4.c kahootReport.c utils.c listElem.c listArrayList.c kahootStatistic.c statisticsUtils.c stringCode.c mapElem.c mapArrayList.c
n5:
	gcc -g -o prog main5.c kahootReport.c utils.c listElem.c listArrayList.c kahootStatistic.c statisticsUtils.c stringCode.c mapElem.c mapArrayList.c