n3:
		gcc -o prog -g main3.c stackElem.c stackArrayList.c

n4:
		gcc -o prog -g main4.c stackElem.c stackArrayList.c queueElem.c queueArrayList.c

n5:
		gcc -o prog -g main5.c stackElem.c stackArrayList.c queueElem.c queueArrayList.c

run:
		./prog